/* Result Preview — app shell.

   Flow: pick a treatment, frame a face, capture, then drag sliders and
   compare against the untouched photo. The camera is only unlocked once
   the model can actually see a usable face, because every one of these
   simulations degrades badly on a three-quarter view and it is far
   cheaper to nag before the shutter than to apologise after it. */

import { initFace, detect, IDX, pt, mid, faceScale, mouthOpenRatio, yaw }
  from "./face.js";
import { applyTeeth } from "./sim-teeth.js";
import { applyNose }  from "./sim-nose.js";
import { applyHair }  from "./sim-hair.js";
import { buildCard, saveCard } from "./export.js";

/* Where "Ask a surgeon" goes. Resolved against the current page so it
   works on the live domain, on a preview deploy, and locally. */
const BOOK_URL = "book.html";

/* Longest edge of the working image. Big enough that a saved card is
   sharp — and too heavy to re-render on every frame of a slider drag. */
const WORK_MAX = 900;

/* So dragging renders a smaller copy and the full one is produced when
   the finger lifts. The warp cost is per-pixel, so this is the
   difference between roughly 8fps and roughly 25fps on a mid-range
   phone, on the one interaction the whole tool is built around. The
   draft is only ever a backing-store change: both canvases are stretched
   to the same box by CSS, so the divider still lines up exactly. */
const DRAFT_MAX = 520;

const $ = s => document.querySelector(s);

const state = {
  treatment: null,
  landmarks: null,
  source: null,        // ImageData of the captured photo, untouched
  facing: "user",
  stream: null,
  params: {},
  raf: 0,
  pending: false
};

/* ── slider definitions ──────────────────────────────────────────── */
const TREATMENTS = {
  dental: {
    label: "Teeth",
    title: "Teeth",
    utm: "dental",
    afterTag: "Illustration",
    sliders: [
      { key: "whiten", label: "Whitening",
        hint: "Shade change only — no shape work", def: 0.55 },
      { key: "align",  label: "Shape & alignment",
        hint: "What crowns or veneers would change", def: 0.5 }
    ],
    disclaimer:
      "<b>Illustration only.</b> Use Before / After above to compare. This image was " +
      "generated by a filter on this phone, has not been seen by a dentist, and " +
      "is not a prediction of your result. What is actually achievable depends " +
      "on your bone, your gums, the teeth you still have, and the plan a dentist " +
      "makes with you in person."
  },
  nose: {
    label: "Nose",
    title: "Nose",
    utm: "nose",
    afterTag: "Illustration",
    sliders: [
      { key: "hump",  label: "Bridge",
        hint: "Straightening the profile line", def: 0.4 },
      { key: "width", label: "Width",
        hint: "Narrowing across the nostrils", def: 0.4 },
      { key: "tip",   label: "Tip",
        hint: "Rotation and refinement", def: 0.35 }
    ],
    disclaimer:
      "<b>Illustration only.</b> The sliders stop at roughly what primary " +
      "rhinoplasty achieves, so what you see here is deliberately modest. Note " +
      "that most of this operation shows in profile, and a photo taken from the " +
      "front cannot show you that. Your bone, your cartilage and your skin " +
      "thickness decide the rest — a surgeon has to look at them."
  },
  /* Hair is a design overlay rather than a simulated photograph. Drawing
     believable hair onto a forehead needs a trained generative model;
     what procedural drawing produced was either a comb of lines or a
     smudge, and neither belongs in front of a patient. Marking up where
     the hairline could go is what a surgeon does at a consultation
     anyway, and it gives the patient a graft number to check. */
  hair: {
    label: "Hair",
    title: "Hairline plan",
    utm: "hair",
    afterTag: "Plan",
    sliders: [
      { key: "hairline", label: "How far forward",
        hint: "Where a surgeon could rebuild the line to", def: 0.6 }
    ],
    disclaimer:
      "<b>A plan, not a result.</b> We are not going to paint fake hair onto " +
      "your photo — those pictures always flatter, and you would find out the " +
      "truth after you had paid. The dashed line is where your hairline sits " +
      "now; the solid line is where it could be rebuilt to. The graft number is " +
      "an estimate from the shaded area and average density. Only an in-person " +
      "check of your donor area can tell you what you actually have to spend."
  }
};

/* ── screens ─────────────────────────────────────────────────────── */
function show(id) {
  document.querySelectorAll(".screen").forEach(s => s.classList.toggle("is-on", s.id === id));
}

/* ── 1. treatment picker ─────────────────────────────────────────── */
document.querySelectorAll("[data-treat]").forEach(btn => {
  btn.addEventListener("click", () => {
    const t = btn.dataset.treat;
    if (t === "knee") {
      $("#btn-book2").href = bookLink("knee");
      show("s-knee");
      return;
    }
    state.treatment = t;
    startCamera();
  });
});

$("#btn-back2").addEventListener("click", () => show("s-pick"));
$("#btn-back").addEventListener("click", () => { stopCamera(); show("s-pick"); });
$("#btn-retake").addEventListener("click", () => startCamera());

function bookLink(t) {
  const u = new URL(BOOK_URL, location.href);
  u.searchParams.set("t", t);
  u.searchParams.set("utm_source", "result-preview");
  u.searchParams.set("utm_medium", "tool");
  u.searchParams.set("utm_campaign", "see-a-result");
  return u.toString();
}

/* ── 2. camera ───────────────────────────────────────────────────── */
const video = $("#video");
const guide = $("#guide");
const hint  = $("#hint");
const shoot = $("#btn-shoot");

async function startCamera() {
  show("s-cam");
  $("#boot").hidden = false;
  $("#boot").style.display = "";
  shoot.disabled = true;

  try {
    await initFace();
  } catch (e) {
    bootError("Could not load the face model. Reload the page and try again.");
    return;
  }

  try {
    state.stream = await navigator.mediaDevices.getUserMedia({
      video: { facingMode: state.facing, width: { ideal: 1280 }, height: { ideal: 1280 } },
      audio: false
    });
  } catch (e) {
    bootError(
      "No camera access. You can still upload a photo from your gallery.",
      true
    );
    return;
  }

  video.srcObject = state.stream;
  await video.play().catch(() => {});
  $("#boot").style.display = "none";
  video.style.transform = state.facing === "user" ? "scaleX(-1)" : "none";
  loop();
}

function bootError(msg, allowUpload) {
  const b = $("#boot");
  b.style.display = "";
  b.innerHTML = `<div><p class="boot__err">${msg}</p>${
    allowUpload ? '<button id="boot-up">Choose a photo</button>' : ""
  }</div>`;
  const up = document.getElementById("boot-up");
  if (up) up.addEventListener("click", () => $("#file").click());
}

function stopCamera() {
  cancelAnimationFrame(state.raf);
  if (state.stream) {
    state.stream.getTracks().forEach(t => t.stop());
    state.stream = null;
  }
}

$("#btn-flip").addEventListener("click", () => {
  stopCamera();
  state.facing = state.facing === "user" ? "environment" : "user";
  startCamera();
});

$("#btn-upload").addEventListener("click", () => $("#file").click());
$("#file").addEventListener("change", async e => {
  const f = e.target.files && e.target.files[0];
  if (!f) return;
  const img = new Image();
  const url = URL.createObjectURL(f);
  img.onload = () => {
    URL.revokeObjectURL(url);
    stopCamera();
    useImage(img, img.naturalWidth, img.naturalHeight, false);
  };
  img.onerror = () => {
    URL.revokeObjectURL(url);
    alert("This phone could not open that picture. Try taking a new photo, " +
          "or pick a different one from your gallery.");
  };
  img.src = url;
  e.target.value = "";
});

/* Live framing check. Runs the detector on a small copy of the frame —
   full resolution here would cost far more than it tells us. */
const probe = document.createElement("canvas");
probe.width = 256; probe.height = 256;
const probeCtx = probe.getContext("2d", { willReadFrequently: true });

let lastProbe = 0;

function loop() {
  state.raf = requestAnimationFrame(loop);
  if (!state.stream || video.readyState < 2) return;

  const now = performance.now();
  if (now - lastProbe < 120) return;    // ~8fps is plenty for a framing nag
  lastProbe = now;

  const vw = video.videoWidth, vh = video.videoHeight;
  if (!vw) return;

  const side = Math.min(vw, vh);
  probeCtx.drawImage(video, (vw - side) / 2, (vh - side) / 2, side, side, 0, 0, 256, 256);

  let lm = null;
  try { lm = detect(probe, 256, 256); } catch (e) { /* transient */ }

  drawGuide(!!lm);

  if (!lm) { setHint("Bring your face into the circle", false); shoot.disabled = true; return; }

  const S = faceScale(lm);
  const y = Math.abs(yaw(lm));

  if (S < 52)      { setHint("Move a little closer", false); shoot.disabled = true; return; }
  if (S > 130)     { setHint("Move back a little", false);   shoot.disabled = true; return; }
  if (y > 0.34)    { setHint("Face the camera straight on", false); shoot.disabled = true; return; }

  if (state.treatment === "dental" && mouthOpenRatio(lm) < 0.07) {
    setHint("Give us a proper smile — we need to see your teeth", false);
    shoot.disabled = true; return;
  }
  if (state.treatment === "hair" && pt(lm, IDX.foreheadTop).y < S * 0.55) {
    setHint("Tilt the phone down — we need the top of your head", false);
    shoot.disabled = true; return;
  }

  setHint("Good — hold still and tap", true);
  shoot.disabled = false;
}

function setHint(text, ok) {
  if (hint.textContent !== text) hint.textContent = text;
  hint.classList.toggle("is-ok", ok);
}

function drawGuide(found) {
  const r = video.getBoundingClientRect();
  if (guide.width !== r.width || guide.height !== r.height) {
    guide.width = r.width; guide.height = r.height;
  }
  const g = guide.getContext("2d");
  g.clearRect(0, 0, guide.width, guide.height);
  const cx = guide.width / 2, cy = guide.height * 0.46;
  const rx = guide.width * 0.34, ry = rx * 1.32;

  g.strokeStyle = found ? "rgba(143,214,208,.9)" : "rgba(255,255,255,.4)";
  g.lineWidth = 2;
  g.setLineDash(found ? [] : [7, 9]);
  g.beginPath();
  g.ellipse(cx, cy, rx, ry, 0, 0, Math.PI * 2);
  g.stroke();
}

shoot.addEventListener("click", () => {
  const vw = video.videoWidth, vh = video.videoHeight;
  const side = Math.min(vw, vh);
  const c = document.createElement("canvas");
  c.width = side; c.height = side;
  const g = c.getContext("2d");
  /* Un-mirror the selfie view, so the saved photo matches what a mirror
     shows rather than what the preview showed. */
  if (state.facing === "user") { g.translate(side, 0); g.scale(-1, 1); }
  g.drawImage(video, (vw - side) / 2, (vh - side) / 2, side, side, 0, 0, side, side);
  stopCamera();
  useImage(c, side, side, true);
});

/* ── 3. result ───────────────────────────────────────────────────── */
const cvBefore = $("#cv-before");
const cvAfter  = $("#cv-after");
const stage    = $("#stage");
const busy     = $("#busy");

function useImage(source, sw, sh, alreadySquare) {
  const scale = Math.min(1, WORK_MAX / Math.max(sw, sh));
  const w = Math.round(sw * scale), h = Math.round(sh * scale);

  const c = document.createElement("canvas");
  c.width = w; c.height = h;
  const g = c.getContext("2d", { willReadFrequently: true });
  g.drawImage(source, 0, 0, w, h);

  let lm = null;
  try { lm = detect(c, w, h); } catch (e) {}

  if (!lm) {
    alert("We could not find a face in that photo. Try again with better light, facing the camera.");
    startCamera();
    return;
  }

  state.landmarks = lm;
  state.source = g.getImageData(0, 0, w, h);

  /* Half-size copy for live dragging, with landmarks scaled to match. */
  const ds = Math.min(1, DRAFT_MAX / Math.max(w, h));
  if (ds < 1) {
    const dw = Math.round(w * ds), dh = Math.round(h * ds);
    const dc = document.createElement("canvas");
    dc.width = dw; dc.height = dh;
    const dg = dc.getContext("2d", { willReadFrequently: true });
    dg.imageSmoothingQuality = "high";
    dg.drawImage(c, 0, 0, dw, dh);
    state.draft = {
      source: dg.getImageData(0, 0, dw, dh),
      lm: lm.map(p => ({ x: p.x * ds, y: p.y * ds, z: p.z })),
      w: dw, h: dh
    };
  } else {
    state.draft = null;
  }

  cvBefore.width = cvAfter.width = w;
  cvBefore.height = cvAfter.height = h;
  cvBefore.getContext("2d").putImageData(state.source, 0, 0);

  fitStage();
  buildSliders();
  setSplit(0.5);
  show("s-res");
  try {
    render(false);
  } catch (err) {
    reportRenderFailure(err);
  }
}

function buildSliders() {
  const def = TREATMENTS[state.treatment];
  $("#res-title").textContent = def.title;
  $("#btn-book").href = bookLink(def.utm);
  $("#tag-after").textContent = def.afterTag;
  $("#disc").innerHTML = def.disclaimer;
  $("#readout").hidden = state.treatment !== "hair";

  state.params = {};
  const host = $("#sliders");
  host.innerHTML = "";

  for (const s of def.sliders) {
    state.params[s.key] = s.def;
    const wrap = document.createElement("div");
    wrap.className = "sld";
    wrap.innerHTML = `
      <div class="sld__row">
        <label class="sld__lb" for="sl-${s.key}">${s.label}
          <span class="sld__hint">${s.hint}</span>
        </label>
        <span class="sld__vl" id="vl-${s.key}"></span>
      </div>
      <input type="range" id="sl-${s.key}" min="0" max="100" step="1" value="${Math.round(s.def * 100)}">`;
    host.appendChild(wrap);

    const input = wrap.querySelector("input");
    const readout = wrap.querySelector(".sld__vl");
    const paint = () => {
      const v = +input.value;
      input.style.setProperty("--fill", v + "%");
      readout.textContent = v === 0 ? "none" : v + "%";
    };
    paint();
    /* "input" fires continuously while dragging — draft quality. */
    input.addEventListener("input", () => {
      state.params[s.key] = +input.value / 100;
      paint();
      schedule(true);
    });
    /* "change" fires once the finger lifts — re-render at full size. */
    input.addEventListener("change", () => {
      state.params[s.key] = +input.value / 100;
      paint();
      schedule(false);
    });
  }
}

$("#btn-reset").addEventListener("click", () => {
  const def = TREATMENTS[state.treatment];
  for (const s of def.sliders) {
    const input = document.getElementById("sl-" + s.key);
    input.value = Math.round(s.def * 100);
    input.dispatchEvent(new Event("change"));
  }
});

/* Coalesce slider movement into one render per frame — a 900px warp is
   far too heavy to run on every input event. */
function schedule(draft) {
  state.wantDraft = draft;
  if (state.pending) return;
  state.pending = true;
  requestAnimationFrame(() => {
    state.pending = false;
    try {
      render(state.wantDraft);
    } catch (err) {
      reportRenderFailure(err);
    }
  });
}

function render(draft) {
  if (!state.source || !state.landmarks) return;

  const use = draft && state.draft ? state.draft : null;
  const src = use ? use.source : state.source;
  const lm  = use ? use.lm : state.landmarks;
  const w   = use ? use.w : state.source.width;
  const h   = use ? use.h : state.source.height;

  if (cvAfter.width !== w || cvAfter.height !== h) {
    cvAfter.width = w; cvAfter.height = h;
  }
  const g = cvAfter.getContext("2d", { willReadFrequently: true });

  let base = src;

  /* Geometry first, then anything painted on top — otherwise the warp
     would smear the teeth or the hairline we just drew. */
  if (state.treatment === "nose") {
    const warped = applyNose(base, lm, state.params);
    if (warped) base = warped;
  }

  g.putImageData(base, 0, 0);

  if (state.treatment === "dental") {
    const r = applyTeeth(g, lm, state.params);
    if (!r.ok) noteProblem(r.reason);
  }
  if (state.treatment === "hair") {
    const r = applyHair(g, lm, state.params);
    if (!r.ok) noteProblem(r.reason);
    showGrafts(r);
  }
}

/* The graft estimate is the number a clinic quotes on, so it is the
   most useful thing this screen can hand the patient — and the easiest
   to over-trust, hence the range and the wording. */
function showGrafts(r) {
  const el = $("#readout");
  if (!r.ok || !r.applied || !r.grafts || !r.grafts[1]) {
    el.innerHTML = "<span class='ro__hint'>Move the slider to plan a new hairline.</span>";
    return;
  }
  el.innerHTML =
    `<span class="ro__n">${r.grafts[0].toLocaleString()}&ndash;${r.grafts[1].toLocaleString()}</span>` +
    `<span class="ro__l">grafts, roughly, to cover ${r.areaCm2.toFixed(1)}&nbsp;cm&sup2;` +
    `<em>Estimated from the photo. A clinic measures this properly.</em></span>`;
}

/* A render that throws used to leave the sliders looking dead with
   nothing on screen to explain it — the failure was invisible to the
   person using it and invisible to us. Now it says so once, and names
   the browser, so a report like "it doesn't work on my mum's phone"
   comes with something to act on. */
let renderFailed = false;
function reportRenderFailure(err) {
  if (renderFailed) return;
  renderFailed = true;
  const disc = $("#disc");
  if (disc) {
    disc.innerHTML =
      "<b>This phone could not draw the preview.</b> " +
      "Everything runs inside your browser, and something here is not " +
      "supported. Updating your browser usually fixes it. If you tell us " +
      "what phone you are on we will get it working: " +
      "<a href=\"mailto:suleymansuleymanoglu@medmatchglobal.info?subject=Preview%20tool%20problem\">" +
      "email us</a>. <span class=\"disc__tech\">" +
      String((err && err.message) || err).slice(0, 120) + "</span>";
  }
}

let notedOnce = "";
function noteProblem(reason) {
  if (notedOnce === reason) return;
  notedOnce = reason;
  const msgs = {
    closed:   "We can barely see your teeth — retake with a wider smile.",
    "no-teeth": "Not enough tooth surface visible to work from. Try again in better light.",
    small:    "Too far away to work on the mouth. Retake a little closer.",
    cropped:  "The top of your head is cut off, so we cannot find your hairline. Retake with the whole head in frame.",
    "no-hair": "We could not pick out a hairline in this photo. Even light and a plain background help.",
    framing:  "Retake with your whole head in frame."
  };
  if (msgs[reason]) setTimeout(() => alert(msgs[reason]), 60);
}

/* Where the saved card should crop to — the part of the face the
   treatment actually changes, sized in multiples of interocular
   distance so it frames the same way at any photo resolution. */
function focusPoint() {
  const lm = state.landmarks;
  if (!lm) return null;
  const S = faceScale(lm);

  if (state.treatment === "dental") {
    const m = mid(pt(lm, IDX.mouthL), pt(lm, IDX.mouthR));
    return { cx: m.x, cy: m.y - S * 0.10, w: S * 2.4 };
  }
  if (state.treatment === "nose") {
    const n = pt(lm, IDX.noseTip);
    return { cx: n.x, cy: n.y - S * 0.05, w: S * 2.3 };
  }
  /* hair — frame the forehead and the planned line, not the chin */
  const t = pt(lm, IDX.foreheadTop);
  return { cx: t.x, cy: t.y + S * 0.30, w: S * 2.8 };
}

/* ── before / after comparison ───────────────────────────────────────
   Three explicit modes behind three labelled buttons, because the wipe
   on its own was a trap. The drag layer covers the whole photo, so a
   single tap anywhere jumped the divider to that point — tap the right
   edge and the "after" is squeezed to nothing, at which point every
   slider looks broken. That is exactly what happened on the first phone
   other than mine that tried it.

   The wipe is still there for anyone who finds it, but it can no longer
   hide either side completely, and it is no longer the only way to see
   the result. */

const stageGrab = $("#grab");
let wipeAt = 0.5;              // remembered wipe position
let view = "wipe";             // "wipe" | "before" | "after"

function applyView() {
  const pct = view === "before" ? 100
            : view === "after"  ? 0
            : Math.max(6, Math.min(94, wipeAt * 100));
  stage.style.setProperty("--split", pct + "%");
  stage.classList.toggle("is-wiping", view === "wipe");
  document.querySelectorAll("[data-view]").forEach(b =>
    b.classList.toggle("is-on", b.dataset.view === view));
}

function setView(v) { view = v; applyView(); }

function setSplit(frac) {
  wipeAt = Math.max(0, Math.min(1, frac));
  view = "wipe";
  applyView();
}

document.querySelectorAll("[data-view]").forEach(btn =>
  btn.addEventListener("click", () => setView(btn.dataset.view)));

/* A press only becomes a wipe once it has actually moved. Without this
   threshold a tap is indistinguishable from a drag, which is how the
   divider used to end up pinned at one edge by accident. */
const DRAG_SLOP = 6;
let down = null;

function pointerX(e) {
  const r = stage.getBoundingClientRect();
  return ((e.touches ? e.touches[0].clientX : e.clientX) - r.left) / r.width;
}

stageGrab.addEventListener("pointerdown", e => {
  down = { x: e.clientX, moved: false };
  try { stageGrab.setPointerCapture(e.pointerId); } catch (err) { /* non-fatal */ }
});

stageGrab.addEventListener("pointermove", e => {
  if (!down) return;
  if (!down.moved && Math.abs(e.clientX - down.x) < DRAG_SLOP) return;
  down.moved = true;
  setSplit(pointerX(e));
});

function endDrag() { down = null; }
stageGrab.addEventListener("pointerup", endDrag);
stageGrab.addEventListener("pointercancel", endDrag);

/* ── save ────────────────────────────────────────────────────────────
   Deliberately not an async handler. Everything up to navigator.share()
   has to run in the same task as the tap or Safari refuses the share,
   which is why this button used to do nothing at all on an iPhone. Card
   building is all synchronous canvas work, so that is fine. */
$("#btn-save").addEventListener("click", () => {
  const def = TREATMENTS[state.treatment];
  let card;
  try {
    card = buildCard(cvBefore, cvAfter, def.label, def.afterTag, focusPoint());
  } catch (e) {
    alert("Could not build the image on this device.");
    return;
  }

  saveCard(card, `medmatch-preview-${state.treatment}.jpg`)
    .then(res => {
      if (!res.ok) {
        alert("Could not save the image on this device. You can still take a screenshot.");
        return;
      }
      /* iPhone: no share sheet and no working download, so show the
         picture and let them do what they already do with pictures. */
      if (res.how === "longpress") showForLongPress(res.blob);
    })
    .catch(() => {
      alert("Could not save the image on this device. You can still take a screenshot.");
    });
});

/* Full-screen image with an instruction. The reliable way to get a
   picture into an iPhone's camera roll when the share sheet is not
   available is for the person to press and hold it themselves. */
function showForLongPress(blob) {
  const url = URL.createObjectURL(blob);

  const wrap = document.createElement("div");
  wrap.className = "saveover";

  const tip = document.createElement("p");
  tip.className = "saveover__tip";
  tip.append("Press and hold the picture, then choose ");
  const strong = document.createElement("b");
  strong.textContent = "Save to Photos";
  tip.append(strong, ".");

  /* Built with its src already set, so the element never exists in a
     state where it could paint as a broken image. */
  const img = document.createElement("img");
  img.alt = "Your preview, ready to save";
  img.src = url;

  const done = document.createElement("button");
  done.className = "saveover__close";
  done.type = "button";
  done.textContent = "Done";

  const close = () => {
    wrap.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  };
  done.addEventListener("click", close);
  wrap.addEventListener("click", e => { if (e.target === wrap) close(); });

  wrap.append(tip, img, done);
  document.querySelector(".app").appendChild(wrap);
}

/* Size the stage to the photo, but never let it eat the screen.

   A portrait upload at full width came out taller than the phone, which
   pushed every slider below the fold — the user was left comparing an
   image with no way to change it without scrolling away from it. So the
   stage is fitted inside both the available width and half the viewport
   height, keeping the photo's aspect exactly so the two canvases stay
   aligned and the divider tracks the pointer. */
function fitStage() {
  if (!state.source) return;
  const iw = cvBefore.width, ih = cvBefore.height;
  const availW = stage.parentElement.clientWidth || 520;
  const availH = Math.max(220, innerHeight * 0.5);
  const scale = Math.min(availW / iw, availH / ih);
  stage.style.width = Math.round(iw * scale) + "px";
  stage.style.height = Math.round(ih * scale) + "px";
}

addEventListener("resize", fitStage);
addEventListener("orientationchange", () => setTimeout(fitStage, 120));
